---
title: "phase2"
author: "Turner Schwiebert"
date: "11/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(data.table)
library(caret)

forwards <- read.csv("../Data Acquisition/Data/forwards10_20_2022.csv")

attmids_wings <- forwards %>% filter(position == "Att Mid / Wing")
attmids_wings$height_cm <- as.numeric(as.character(attmids_wings$height_cm))

forwards <- forwards %>% filter(position == "Forward")
forwards$height_cm <- as.numeric(as.character(forwards$height_cm))

centerbacks <- read.csv("../Data Acquisition/Data/centerbacks10_20_2022.csv")
centerbacks$height_cm <- as.numeric(as.character(centerbacks$height_cm))

fullbacks <- read.csv("../Data Acquisition/Data/fullbacks10_20_2022.csv")
fullbacks$height_cm <- as.numeric(as.character(fullbacks$height_cm))

midfielders <- read.csv("../Data Acquisition/Data/midfielders10_20_2022.csv")
midfielders$height_cm <- as.numeric(as.character(midfielders$height_cm))
```

# Clustering Forwards

```{r}
for_clusters <- hclust(dist(forwards[, c(6,7,20:146)]))
plot(for_clusters)
firstcut <- cutree(for_clusters, 3)
forwards_clust <- forwards
forwards_clust$h_cluster <- firstcut
```

```{r}
FiveFit = kmeans(forwards[,20:146], 5, nstart=50)
forwards_clust$k_cluster <- FiveFit$cluster
```


# Visuals

```{r}
filter(forwards_clust, k_clusters==2)

for_xG_vec = numeric(5)
for_DT_vec = numeric(5)

for(i in 1:5){
  for_xG_vec[i] = mean(filter(forwards_clust, forwards_clust$k_cluster==i)$xG)
  for_DT_vec[i] = mean(filter(forwards_clust, forwards_clust$k_cluster==i)$Dribblers.Tackled)
}

barplot(for_xG_vec ~ c(1:5), xlab = "Cluster", ylab= "Expected Goals", main = "xG per 90 by Cluster")
barplot(for_DT_vec ~ c(1:5), xlab = "Cluster", ylab= "Dribblers Tackled", main = "Dribblers Tackled per 90 by Cluster")
```





