---
title: "EarlyFindings"
author: "Turner Schwiebert"
date: "10/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data

```{r}
library(dplyr)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(data.table)
players <- read.csv("../Data Acquisition/Data/players.csv")
players$height_cm <- as.numeric(as.character(players$height_cm))
```

# Clustering

```{r}
clusters <- hclust(dist(players[, c(6,7,20:146)]))
plot(clusters)
firstcut <- cutree(clusters, 14)
table(players$position, firstcut)
cluster_prev <- table(players$position, firstcut)
cluster_prev
players_clust <- players
players_clust$cluster <- firstcut
```

# Visuals

```{r, offensive/defensive output visuals}
xG_vec = numeric(14)
DT_vec = numeric(14)
for(i in 1:14){
  xG_vec[i] = mean(filter(players_clust, players_clust$cluster==i)$xG)
  DT_vec[i] = mean(filter(players_clust, players_clust$cluster==i)$Dribblers.Tackled)
}
barplot(xG_vec ~ c(1:14), xlab = "Cluster", ylab= "Expected Goals", main = "xG per 90 by Cluster")
barplot(DT_vec ~ c(1:14), xlab = "Cluster", ylab= "Dribblers Tackled", main = "Dribblers Tackled per 90 by Cluster")
```

```{r, positional prevalence visuals}
positions = c("Att Mid / Wing", "Center Back", "Forward", "Fullback", "Midfielder")

plots <- lapply(1:14, function(x) ggplot(filter(players_clust,cluster == x), aes(x = position)) +
    geom_bar(fill = "black", width = 0.7)+
    theme_base()+
    theme(text =element_text(size = 15), axis.text.x = element_text(size = 13))+
    labs(x = "Position", y = "Count", title = sprintf("Cluster %s", x)))
figure1234 <- ggarrange(plots[[1]], plots[[2]], plots[[3]], plots[[4]], nrow = 2, ncol = 2)
figure5678 <- ggarrange(plots[[5]], plots[[6]], plots[[7]], plots[[8]], nrow = 2, ncol = 2)
figure9101112 <- ggarrange(plots[[9]], plots[[10]], plots[[11]], plots[[12]], nrow = 2, ncol = 2)
figure1314 <- ggarrange(plots[[13]], plots[[14]], nrow = 2, ncol = 2)
figure1234
figure5678
figure9101112
figure1314
```

```{r, begin investigating within position}
p <- ggplot(data = players, aes(x = xG, y = Dribblers.Tackled)) + geom_point()
p + facet_wrap(~position) + labs(title = "Dribblers Tackled vs. Expected Goals (per 90 minutes) by Position", y = "Dribblers Tackled per 90", 
                                 x = "Expected Goals per 90")
```



